# Docker Compose for local development
# Handles platform differences automatically

version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ace_app_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  screenshot-service:
    build: 
      context: ./screenshot_service
      dockerfile: Dockerfile
      # Docker will automatically select the right platform
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
    volumes:
      # Mount screenshots directory for local development
      - ./priv/static/screenshots:/home/pptruser/app/screenshots

  ace-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development  # We can add a dev target later
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/ace_app_dev
      SCREENSHOT_SERVICE_URL: http://screenshot-service:3001
      SECRET_KEY_BASE: dev_secret_key_base_that_is_at_least_64_characters_long_for_development
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID:-test_client_id}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET:-test_client_secret}
    depends_on:
      - postgres
      - screenshot-service
    volumes:
      - .:/app
      - /app/deps
      - /app/_build

volumes:
  postgres_data: