import Config

# Configure your database
config :ace_app, AceApp.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "ace_app_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  log: false

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :ace_app, AceAppWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "bSVtTvmVx8QediRZjJe2EffHFnUjyO824F8efTSIVPM+wo52zwe2oLMDNMly36gl",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:ace_app, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:ace_app, ~w(--watch)]}
  ]

# Telemetry configuration for development
config :ace_app, :telemetry,
  # Disable periodic measurements during development to reduce noise
  # Set to true to enable metrics collection for testing
  enable_periodic_measurements: false

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :ace_app, AceAppWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ace_app_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :ace_app, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Screenshot service configuration for development
config :ace_app,
  base_url: System.get_env("BASE_URL") || "http://host.docker.internal:4000",
  screenshot_service_url: System.get_env("SCREENSHOT_SERVICE_URL") || "http://192.168.107.2:3001"

# Discord OAuth Configuration for development
# Replace the placeholder values with your actual Discord application credentials
config :ace_app, :discord_oauth,
  client_id: System.get_env("DISCORD_CLIENT_ID") || "1305307752574484511",
  client_secret: System.get_env("DISCORD_CLIENT_SECRET") || "__n7pvhmHzur7EVT3zb5vtCDUJcI_wTu",
  redirect_uri: "http://localhost:4000/auth/discord/callback"

# Admin Discord IDs (comma-separated string of Discord user IDs)
# Replace with your actual Discord user ID to get admin privileges
config :ace_app, :admin_discord_ids,
  System.get_env("ADMIN_DISCORD_IDS") || "113427839272898560"
